security:

    #-----------------------------------------------#
    #---- SISTEMA DE CODIFICACIÓN DE CONTRASEÑAS ---#
    #-----------------------------------------------#
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false


    #-----------------------------------------------#
    #--------------- HERENCIA DE ROLES -------------#
    #-----------------------------------------------#
    role_hierarchy:
        ROLE_ADMIN: [ROLE_REGISTRADO]



    #-----------------------------------------------#
    #------------ PROVEEDORES DE USUARIOS ----------#
    #-----------------------------------------------#
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: ROLE_ADMIN }
        user_db:
            entity: { class: AppBundle:User, property: username }


    #-----------------------------------------------#
    #-------- CORTAFUEGO ÁREA PÚBLICA/PRIVADA ------#
    #-----------------------------------------------#
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backEnd:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true


    #---------------------------------------------#
    #-------- CONTROL DE ACCESO ROL/RECURSO ------#
    #---------------------------------------------#
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /admin, roles: [ROLE_REGISTRADO] } -#
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }